import { IMAGES } from '../configs';

export const bestSeller = [
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 15,
    price: 30000,
    product: 'Minuman 1',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 8,
    price: 10500,
    product: 'Minuman 2',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 55,
    price: 12000,
    product: 'Minuman 3',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 4',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 5',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 15,
    price: 30000,
    product: 'Minuman 6',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 8,
    price: 10500,
    product: 'Minuman 7',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 55,
    price: 12000,
    product: 'Minuman 8',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 9',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 10',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 15,
    price: 30000,
    product: 'Makanan 1',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 8,
    price: 10500,
    product: 'Makanan 2',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 55,
    price: 12000,
    product: 'Makanan 3',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Makanan 4',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Makanan 5',
  },
];
