import { IMAGES } from '../configs';

export const bestSeller = [
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 15,
    price: 30000,
    product: 'Minuman 1',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 8,
    price: 10500,
    product: 'Minuman 2',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 55,
    price: 12000,
    product: 'Minuman 3',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 4',
  },
  {
    id: 1,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 5',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 15,
    price: 30000,
    product: 'Minuman 6',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 8,
    price: 10500,
    product: 'Minuman 7',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 55,
    price: 12000,
    product: 'Minuman 8',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 9',
  },
  {
    id: 2,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Minuman 10',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 15,
    price: 30000,
    product: 'Makanan 1',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 8,
    price: 10500,
    product: 'Makanan 2',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 55,
    price: 12000,
    product: 'Makanan 3',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Makanan 4',
  },
  {
    id: 3,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10000,
    product: 'Makanan 5',
  },
  {
    id: 4,
    img: IMAGES.PRODUCT,
    sold: 15,
    price: 40000,
    product: 'Makanan 6',
  },
  {
    id: 4,
    img: IMAGES.PRODUCT,
    sold: 55,
    price: 12500,
    product: 'Makanan 7',
  },
  {
    id: 4,
    img: IMAGES.PRODUCT,
    sold: 25,
    price: 12000,
    product: 'Makanan 8',
  },
  {
    id: 4,
    img: IMAGES.PRODUCT,
    sold: 2,
    price: 10000,
    product: 'Makanan 9',
  },
  {
    id: 4,
    img: IMAGES.PRODUCT,
    sold: 5,
    price: 10040,
    product: 'Makanan 10',
  },

  {
    id: 5,
    img: IMAGES.PRODUCT,
    sold: 35,
    price: 52000,
    product: 'Makanan 11',
  },
  {
    id: 5,
    img: IMAGES.PRODUCT,
    sold: 37,
    price: 12500,
    product: 'Makanan 12',
  },
  {
    id: 5,
    img: IMAGES.PRODUCT,
    sold: 23,
    price: 12000,
    product: 'Makanan 13',
  },
  {
    id: 5,
    img: IMAGES.PRODUCT,
    sold: 33,
    price: 10000,
    product: 'Makanan 14',
  },
  {
    id: 5,
    img: IMAGES.PRODUCT,
    sold: 88,
    price: 10040,
    product: 'Makanan 15',
  },
];
